### ISSUE TITLE
Campos não documentados no antifraude do split de pagamentos

### ISSUE THREAD

**Issue by jvretamero** [Braspag/braspag.github.io#106]
No [documento que descreve a plataforma Antifraude](https://braspag.github.io//manual/split-pagamentos-braspag-antifraude) existem dois campos que aparecem no exemplo da requisição mas não tem detalhamento sobre obrigatoriedade ou tamanho destes campos:

* `Payment.FraudAnalysis.Browser.IpAddress`
* `Payment.FraudAnalysis.Cart.Items[].UnitPrice`

**Comment by aasitamk** [comment]
Campos aparecem atualizados com os detalhes sobre obrigatoriedade e tamanho.
