### ISSUE TITLE
Silent Order Post em sandbox/dev

### ISSUE THREAD

**Issue by czmarcos** [Braspag/braspag.github.io#407]
Opa, blz?

Pelo o que entendi o serviço do "Cartão Protegido" é cobrado como um serviço adicional, mas não entendi se o "Silent Order Post" também seria pago junto com esse serviço ou se seria gratuito. Alguém sabe?

Além disso, estou tentando testar em sandbox com o meu MerchantID de teste, porém está retornando 401. Preciso solicitar alguma ativação desse serviço também na minha conta de teste ou tem alguma chave aberta?

Na documentação fala sobre cadastrar um "IP de saída". Seria cadastrar IP ou o domínio, pois minha aplicação se encontra no Firebase (sem ip estático), nesse caso como faço?

PS: tentei também com o MerchantID desse exemplo, mas também não funciona:
https://github.com/Braspag/braspag.github.io/blob/docs/_i18n/pt/_posts/silent-order-post-example.html

Valeu!

**Comment by aasitamk** [comment]
Olá, @czmarcos! Para tirar dúvidas a respeito da utilização das APIs da Braspag, você pode entrar em contato diretamente por um dos canais de suporte, como explicado nesta página: https://suporte.braspag.com.br/hc/pt-br/articles/360006721672-Atendimento-Braspag.
Aqui no github você irá encontrar somente o repositório dos manuais da empresa, mesmo.

Espero ter ajudado. :)
