### ISSUE TITLE
Sand Box Pagador 401 Unauthorized

### ISSUE THREAD

**Issue by vinisdl** [Braspag/braspag.github.io#5]
Bom dia, 
Estou fazendo uma integração, 
Me cadastrei no sandBox, Estou fazendo o request mais básico pelo Postman

Headers 
"MerchantKey","value":"XXXX",
"MerchantId","value":"XXX",
"Content-Type", "application/json"

```json
{
   "MerchantOrderId":"1",
   "Customer":{
      "Name":"Nome do Cliente"
   },
   "Payment":{
     "Provider":"Simulado",
     "Type":"CreditCard",
     "Amount":10000,
     "Capture":true,
     "Installments":1,
     "CreditCard":{
         "CardNumber":"4551870000000181",
         "Holder":"Nome do Portador",
         "ExpirationDate":"12/2021",
         "SecurityCode":"123",
         "Brand":"Visa"
     }
   }
}
```

![image](https://user-images.githubusercontent.com/6885761/34107992-6e58aefa-e3e5-11e7-9c0a-e17a28e185a2.png)

Aguardo retorno

**Comment by netojoaobatista** [comment]
Se você está fazendo o teste no sandbox, é **fundamental** que utilize as credenciais de teste, como instruído no manual, na seção sobre os ambientes e sobre o [sandbox](https://braspag.github.io//manual/braspag-pagador#ambiente-sandbox). O erro http 401 é justamente sobre isso: a requisição não foi autorizada por utilização de credenciais inválidas.

**Comment by vinisdl** [comment]
Estou fazendo exatamente isto, ja criei 2 acessos pelo link
https://cadastrosandbox.braspag.com.br/Home/Register
porém sempre me retorna o mesmo erro.
